# Generated by Django 5.0.4 on 2024-04-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myformsapp', '0002_alter_mymodel_field2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='field1',
            new_name='Nombre',
        ),
    ]
