# Generated by Django 5.0.4 on 2024-04-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myformsapp', '0004_rename_field2_mymodel_profesion_mymodel_mensaje_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='Profesion',
            new_name='Motivo',
        ),
    ]
